
# NVIDIA (Maxwell/Pascal/Volta without GSP firmware)
env = NVD_BACKEND,egl
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Fractional scaling support
env = WLR_FRACTIONAL_SCALE,1

xwayland {
    force_zero_scaling = true
}
